[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/fetch-notion"
  to = "/.netlify/functions/fetch-notion"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
